##
## Program 3 Makefile
## CS376.502
## Author: Justin Head (jxh122430@utdallas.edu
##

CXX=g++
CXXFLAGS="-Wall"
OBJS=program3.o

all: program3

clean:
	rm -f $(OBJS) *.o program3

program3: $(OBJS)
	$(CXX) -o $@ $(OBJS) 
